#!/bin/bash
#
# Compiles to JAR file and move JAR to destination argument.
#
# Args:
#  $1 = Destination directory for JAR file
#

destination=$1

version=`cat version.txt`
filename="script-elements-${version}.jar"
javac -sourcepath src -cp "lib/*" -d bin @sources.txt
cd bin
jar cvf $filename *
mv $filename $destination
